# Generated by Django 4.1 on 2023-03-16 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="registered_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
