# Generated by Django 4.1 on 2023-03-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0021_event_is_expired"),
        ("store", "0003_storeorder_storeorderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeorder",
            name="cafe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_orders",
                to="cafe.cafe",
            ),
        ),
    ]
