# Generated by Django 4.1 on 2023-05-20 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_order_count_alter_storeorder_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeorder",
            name="phone_number",
        ),
    ]
