# Generated by Django 4.1 on 2023-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_storeorder_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="adding_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_choice",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="storeorder",
            name="postal_code",
            field=models.CharField(max_length=11),
        ),
    ]
