# Generated by Django 4.1 on 2023-05-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_product_adding_count_product_minimum_choice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
