# Generated by Django 4.1 on 2023-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="test",
        ),
    ]
