# Generated by Django 4.1 on 2022-09-05 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(default='slug', max_length=125),
            preserve_default=False,
        ),
    ]
