# Generated by Django 4.1 on 2022-12-09 17:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="desc",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
