# Generated by Django 4.1 on 2022-11-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.comment'),
        ),
    ]
