# Generated by Django 4.1 on 2024-03-19 16:07

import cloud.vaidators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cafe", "0033_alter_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudyCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[cloud.vaidators.PhoneValidator],
                    ),
                ),
                ("fullName", models.CharField(blank=True, max_length=255)),
                ("is_called", models.BooleanField(default=False)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_deployed", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("called_date", models.DateTimeField(blank=True, null=True)),
                ("confirmed_date", models.DateTimeField(blank=True, null=True)),
                ("deployed_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cloudies",
                        to="cafe.cafe",
                    ),
                ),
            ],
        ),
    ]
