# Generated by Django 4.1 on 2024-03-19 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0033_alter_category_image"),
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudycustomer",
            name="cafe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cloud",
                to="cafe.cafe",
            ),
        ),
    ]
