# Generated by Django 4.1 on 2024-03-19 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0002_alter_cloudycustomer_cafe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudycustomer",
            name="phone",
        ),
    ]
