name: Cafe Iran Docker CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker Compose
      run: make up
    - name: Monitor Logs
      run: make show_logs
    - name: Take Test From CafeIran App
      run: make test 
  
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Connect & Execute Commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          script: ls