name: Cafe Iran Docker CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker Compose
      run: make up
    - name: Monitor Logs
      run: make show_logs
    - name: Take Test From CafeIran App
      run: make test 
  
  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Connect & Execute Commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          script: |
            cd ${{secrets.BACK_PATH}}
            git pull --no-ff
            source venv/bin/activate
            pip install -r requirements2.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx