# Generated by Django 4.1 on 2022-09-06 06:26

import cafe.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0002_city_slug_province_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('persian_title', models.CharField(max_length=85)),
                ('english_title', models.CharField(max_length=90)),
                ('slug', models.SlugField(max_length=200)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[cafe.validators.PhoneValidator])),
                ('email', models.EmailField(max_length=125)),
                ('image_url', models.URLField(max_length=250)),
                ('telegram_id', models.CharField(max_length=100)),
                ('instagram_id', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('google_map_url', models.URLField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('short_desc', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected')], default='P', max_length=1)),
                ('type', models.CharField(choices=[('C', 'CAFE'), ('R', 'RESTAURANT'), ('CR', 'CAFE_RESTAURANT')], default='C', max_length=2)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='province.city')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='province.province')),
            ],
        ),
    ]
