# Generated by Django 4.1 on 2022-09-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_order_code_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='postal_code',
        ),
    ]
