# Generated by Django 4.1 on 2022-09-12 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0003_alter_cafe_email_alter_cafe_google_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='type',
            field=models.CharField(choices=[('C', 'CAFE'), ('R', 'RESTAURANT'), ('CR', 'CAFE_RESTAURANT'), ('IC', 'ICE_CREAM_PARLOR')], default='C', max_length=2),
        ),
    ]
