# Generated by Django 4.1 on 2022-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0004_order_desc_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="num_of_table",
            field=models.IntegerField(default=0),
        ),
    ]
