# Generated by Django 4.1 on 2022-09-12 13:22

import cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_cafe_owner_alter_cafe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72)),
                ('image', models.ImageField(upload_to=cafe.models.category_image_file_path)),
            ],
        ),
    ]
