# Generated by Django 4.1 on 2022-09-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0006_cafe_charge_expired_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="latitude",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name="cafe",
            name="longitude",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
