# Generated by Django 4.1 on 2022-09-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_cafe_latitude_cafe_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
