# Generated by Django 4.1 on 2022-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(max_length=250),
        ),
    ]
