# Generated by Django 4.1 on 2022-09-15 05:59

import cafe.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_alter_cafe_slug_alter_menuitem_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('image', models.ImageField(upload_to=cafe.models.gallery_image_file_path)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cafe.cafe')),
            ],
        ),
    ]
