# Generated by Django 4.1 on 2022-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='google_map_url',
            field=models.URLField(blank=True, error_messages={'invalid': 'مقدار وارد شده صحیح نم باشد'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image_url',
            field=models.URLField(blank=True, error_messages={'invalid': 'مقدار وارد شده صحیح نم باشد'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(error_messages={'invalid': 'مقدار وارد شده صحیح نم باشد'}, max_length=250),
        ),
    ]
