# Generated by Django 4.1 on 2022-10-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0010_bartender_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='cafe.cafe')),
                ('users', models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
