# Generated by Django 4.1 on 2022-09-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_reservation_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
