# Generated by Django 4.1 on 2022-12-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0015_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="calorie",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
