# Generated by Django 4.1 on 2023-01-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0018_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
