# Generated by Django 4.1 on 2023-02-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0020_event_date_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
