# Generated by Django 4.1 on 2023-05-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("province", "0001_initial"),
        ("cafe", "0022_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="branches",
                to="province.city",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="branches",
                to="province.province",
            ),
        ),
    ]
