# Generated by Django 4.1 on 2023-07-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0023_alter_branch_city_alter_branch_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="menu_url",
            field=models.URLField(
                blank=True,
                error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                max_length=250,
                null=True,
            ),
        ),
    ]
