# Generated by Django 4.1 on 2023-08-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0025_alter_menuitem_image_url_alter_orderitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="tax",
            field=models.SmallIntegerField(default=0),
        ),
    ]
