# Generated by Django 4.1 on 2023-09-27 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0027_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("number", "cafe")},
        ),
    ]
