# Generated by Django 4.1 on 2023-10-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0028_alter_table_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="is_notify_expired_from_back",
            field=models.CharField(
                choices=[
                    ("I", "Informed"),
                    ("N", "Need To Be Informed"),
                    ("C", "Charged"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="is_notify_expired_from_front",
            field=models.CharField(
                choices=[
                    ("I", "Informed"),
                    ("N", "Need To Be Informed"),
                    ("C", "Charged"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
