# Generated by Django 4.1 on 2023-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0030_menuitem_sort_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="sort_index",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
