# Generated by Django 4.1 on 2024-01-05 15:03

import cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0032_category_cafe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=cafe.models.category_image_file_path
            ),
        ),
    ]
