# Generated by Django 4.1 on 2024-04-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0033_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
