# Generated by Django 4.1 on 2022-09-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_contactus_alter_aboutus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contactus', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
