# Generated by Django 4.1 on 2022-11-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_robots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name_plural': 'Robots'},
        ),
    ]
