# Generated by Django 4.1 on 2023-09-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0004_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="error",
            name="reference",
            field=models.CharField(max_length=325),
        ),
    ]
